apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "oracle-database-operator.metricsCertificateName" . }}
  namespace: {{ include "oracle-database-operator.namespace" . }}
  labels:
    {{- include "oracle-database-operator.labels" . | nindent 4 }}
spec:
  subject:
    organizations:
    - {{ include "oracle-database-operator.name" . }}
  dnsNames:
  - {{ include "oracle-database-operator.metricsServiceName" . }}.{{ include "oracle-database-operator.namespace" . }}.svc
  - {{ include "oracle-database-operator.metricsServiceName" . }}.{{ include "oracle-database-operator.namespace" . }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "oracle-database-operator.issuerName" . }}
  secretName: metrics-server-cert
