{{- $namespace := include "oracle-database-operator.namespace" . -}}
{{- if ne $namespace .Release.Namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "oracle-database-operator.labels" . | nindent 4 }}
{{- end }}
