apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "oracle-database-operator.certManagerInjectAnnotation" . }}
  name: {{ include "oracle-database-operator.clusterName" . }}-validating-webhook-configuration
  labels:
    {{- include "oracle-database-operator.labels" . | nindent 4 }}
webhooks:
{{- $webhooks := (fromJson (.Files.Get "files/webhooks.json")).validating }}
{{- range $webhook := $webhooks }}
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "oracle-database-operator.webhookServiceName" $ }}
      namespace: {{ include "oracle-database-operator.namespace" $ }}
      path: {{ $webhook.path }}
  failurePolicy: {{ $.Values.webhook.failurePolicy }}
  name: {{ $webhook.name }}
  matchPolicy: {{ $webhook.matchPolicy }}
  timeoutSeconds: {{ $.Values.webhook.timeoutSeconds }}
  {{- include "oracle-database-operator.webhookNamespaceSelector" $ | nindent 2 }}
  rules:
  - apiGroups:
    - {{ $webhook.apiGroup }}
    apiVersions:
    - {{ $webhook.apiVersion }}
    operations:
    {{- range $webhook.operations }}
    - {{ . }}
    {{- end }}
    resources:
    - {{ $webhook.resources }}
  sideEffects: None
{{- end }}
